sudo: required
services:
    - docker

before_install:
    - docker build -t alassani/automated-builds .

script:
    # - docker run -e CI=true alassani/docker-react
    - echo 'Alassani ABODJI has finished the build !'

after_install:
    -
